# Generated by Django 4.1.5 on 2023-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_conversation_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
