# Generated by Django 4.1.5 on 2023-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_alter_conversation_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
